# Generated by Django 3.2.4 on 2021-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='printed_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Printed date: '),
        ),
    ]
