# Generated by Django 3.2.4 on 2021-06-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
